name:                zippers-on-derivatives
version:             0.1.0.0
github:              "githubuser/zippers-on-derivatives"
license:             BSD-3-Clause
author:              "Rachel Pham"
maintainer:          "rachel.pham@kcl.ac.uk"
copyright:           "2024 Rachel Pham"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/zippers-on-derivatives#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec >= 2.11.10
- QuickCheck >= 2.14.3
- hspec-discover
- memoize >= 1.1.2
- criterion >= 1.6.4.0
- deepseq >= 1.4.8.1

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-cse
- -fno-full-laziness
library:
  source-dirs: src

executables:
  zippers-on-derivatives-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zippers-on-derivatives
    - containers

tests:
  zippers-on-derivatives-test:
    main:                Spec.hs
    source-dirs:         
    - test
    - test/arbitrary
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zippers-on-derivatives

benchmarks:
  load-testing:
    main: app/benchmarks/LoadTest.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives

  rexp-matching:
    main: app/benchmarks/Rexp.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives

  edelmann-matching:
    main: app/benchmarks/EdelmannZipper.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives

  rexpzipper-matching:
    main: app/benchmarks/RexpZipper.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives

  rexpzipperv2-matching:
    main: app/benchmarks/RexpZipperv2.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives

  edelmann:
    main: app/benchmarks/Edelmann.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives 
  
  urban:
    main: app/benchmarks/Urban.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives 
  
  zipper-lexer:
    main: app/benchmarks/ZipperLexer.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives 
  
  zipper-lexerv2:
    main: app/benchmarks/ZipperLexerv2.hs
    ghc-options:
      - -threaded
      - -rtsopts
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - zippers-on-derivatives
